/* Configuration for day03b generated by Alire */
#ifndef DAY03B_CONFIG_H
#define DAY03B_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "day03b"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
